-- CreateTable
CREATE TABLE "SiteAppearance" (
    "id" TEXT NOT NULL DEFAULT 'site',
    "headerLogoPath" TEXT,
    "headerLogoWidth" INTEGER,
    "headerLogoHeight" INTEGER,
    "faviconPath" TEXT,
    "faviconWidth" INTEGER,
    "faviconHeight" INTEGER,
    "homeBackgroundPath" TEXT,
    "homeBackgroundWidth" INTEGER,
    "homeBackgroundHeight" INTEGER,
    "homeDesktopPositionX" DOUBLE PRECISION,
    "homeDesktopPositionY" DOUBLE PRECISION,
    "homeMobilePositionX" DOUBLE PRECISION,
    "homeMobilePositionY" DOUBLE PRECISION,
    "catalogueBackgroundPath" TEXT,
    "catalogueBackgroundWidth" INTEGER,
    "catalogueBackgroundHeight" INTEGER,
    "catalogueDesktopPositionX" DOUBLE PRECISION,
    "catalogueDesktopPositionY" DOUBLE PRECISION,
    "catalogueMobilePositionX" DOUBLE PRECISION,
    "catalogueMobilePositionY" DOUBLE PRECISION,
    "itemDetailBackgroundPath" TEXT,
    "itemDetailBackgroundWidth" INTEGER,
    "itemDetailBackgroundHeight" INTEGER,
    "itemDetailDesktopPositionX" DOUBLE PRECISION,
    "itemDetailDesktopPositionY" DOUBLE PRECISION,
    "itemDetailMobilePositionX" DOUBLE PRECISION,
    "itemDetailMobilePositionY" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SiteAppearance_pkey" PRIMARY KEY ("id")
);
